## @file
# Standardized Error Hanlding infrastructures.
#
# Copyright (c) 20087, Intel Corporation
# All rights reserved. This program and the accompanying materials
# are licensed and made available under the terms and conditions of the BSD License
# which accompanies this distribution.  The full text of the license may be found at
# http://opensource.org/licenses/bsd-license.php
#
# THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "AS IS" BASIS,
# WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.
#

ERROR_GENERAL_CHECK_ALL = 1000
ERROR_GENERAL_CHECK_NO_TAB = 1001
ERROR_GENERAL_CHECK_INDENTATION = 1002
ERROR_GENERAL_CHECK_LINE = 1003
ERROR_GENERAL_CHECK_NO_ASM = 1004
ERROR_GENERAL_CHECK_NO_PROGMA = 1005
ERROR_GENERAL_CHECK_CARRIAGE_RETURN = 1006
ERROR_GENERAL_CHECK_FILE_EXISTENCE = 1007

ERROR_SPACE_CHECK_ALL = 2000

ERROR_PREDICATE_EXPRESSION_CHECK_ALL = 3000
ERROR_PREDICATE_EXPRESSION_CHECK_BOOLEAN_VALUE = 3001
ERROR_PREDICATE_EXPRESSION_CHECK_NO_BOOLEAN_OPERATOR = 3002
ERROR_PREDICATE_EXPRESSION_CHECK_COMPARISON_NULL_TYPE = 3003

ERROR_HEADER_CHECK_ALL = 4000
ERROR_HEADER_CHECK_FILE = 4001
ERROR_HEADER_CHECK_FUNCTION = 4001

ERROR_C_FUNCTION_LAYOUT_CHECK_ALL = 5000
ERROR_C_FUNCTION_LAYOUT_CHECK_RETURN_TYPE = 5001
ERROR_C_FUNCTION_LAYOUT_CHECK_OPTIONAL_FUNCTIONAL_MODIFIER = 5002
ERROR_C_FUNCTION_LAYOUT_CHECK_FUNCTION_NAME = 5003
ERROR_C_FUNCTION_LAYOUT_CHECK_FUNCTION_PROTO_TYPE = 5004
ERROR_C_FUNCTION_LAYOUT_CHECK_FUNCTION_BODY = 5005
ERROR_C_FUNCTION_LAYOUT_CHECK_DATA_DECLARATION = 5006
ERROR_C_FUNCTION_LAYOUT_CHECK_NO_INIT_OF_VARIABLE = 5007
ERROR_C_FUNCTION_LAYOUT_CHECK_NO_STATIC = 5008

ERROR_INCLUDE_FILE_CHECK_ALL = 6000
ERROR_INCLUDE_FILE_CHECK_IFNDEF_STATEMENT = 6001
ERROR_INCLUDE_FILE_CHECK_DATA = 6002

ERROR_DECLARATION_DATA_TYPE_CHECK_ALL = 7000
ERROR_DECLARATION_DATA_TYPE_CHECK_NO_USE_C_TYPE = 7001
ERROR_DECLARATION_DATA_TYPE_CHECK_IN_OUT_MODIFIER = 7002
ERROR_DECLARATION_DATA_TYPE_CHECK_EFI_API_MODIFIER = 7003
ERROR_DECLARATION_DATA_TYPE_CHECK_ENUMERATED_TYPE = 7004
ERROR_DECLARATION_DATA_TYPE_CHECK_STRUCTURE_DECLARATION = 7005
ERROR_DECLARATION_DATA_TYPE_CHECK_UNION_TYPE = 7006

ERROR_NAMING_CONVENTION_CHECK_ALL = 8000
ERROR_NAMING_CONVENTION_CHECK_DEFINE_STATEMENT = 8001
ERROR_NAMING_CONVENTION_CHECK_TYPEDEF_STATEMENT = 8002
ERROR_NAMING_CONVENTION_CHECK_IFNDEF_STATEMENT = 8003
ERROR_NAMING_CONVENTION_CHECK_PATH_NAME = 8004
ERROR_NAMING_CONVENTION_CHECK_VARIABLE_NAME = 8005
ERROR_NAMING_CONVENTION_CHECK_FUNCTION_NAME = 8006
ERROR_NAMING_CONVENTION_CHECK_SINGLE_CHARACTER_VARIABLE = 8007

ERROR_DOXYGEN_CHECK_ALL = 9000
ERROR_DOXYGEN_CHECK_FILE_HEADER = 9001
ERROR_DOXYGEN_CHECK_FUNCTION_HEADER = 9002
ERROR_DOXYGEN_CHECK_COMMENT_DESCRIPTION = 9003
ERROR_DOXYGEN_CHECK_COMMENT_FORMAT = 9004
ERROR_DOXYGEN_CHECK_COMMAND = 9005

ERROR_META_DATA_FILE_CHECK_ALL = 10000
ERROR_META_DATA_FILE_CHECK_PATH_NAME = 10001
ERROR_META_DATA_FILE_CHECK_LIBRARY_INSTANCE = 10002
ERROR_META_DATA_FILE_CHECK_LIBRARY_INSTANCE_DEPENDENT = 10003
ERROR_META_DATA_FILE_CHECK_LIBRARY_INSTANCE_ORDER = 10004
ERROR_META_DATA_FILE_CHECK_LIBRARY_NO_USE = 10005
ERROR_META_DATA_FILE_CHECK_BINARY_INF_IN_FDF = 10006
ERROR_META_DATA_FILE_CHECK_PCD_DUPLICATE = 10007
ERROR_META_DATA_FILE_CHECK_PCD_FLASH = 10008
ERROR_META_DATA_FILE_CHECK_PCD_NO_USE = 10009
ERROR_META_DATA_FILE_CHECK_DUPLICATE_GUID = 10010
ERROR_META_DATA_FILE_CHECK_DUPLICATE_PROTOCOL = 10011
ERROR_META_DATA_FILE_CHECK_DUPLICATE_PPI = 10012

ERROR_SPELLING_CHECK_ALL = 11000

gEccErrorMessage = {
    ERROR_GENERAL_CHECK_ALL : "",
    ERROR_GENERAL_CHECK_NO_TAB : "",
    ERROR_GENERAL_CHECK_INDENTATION : "",
    ERROR_GENERAL_CHECK_LINE : "",
    ERROR_GENERAL_CHECK_NO_ASM : "",
    ERROR_GENERAL_CHECK_NO_PROGMA : "",
    ERROR_GENERAL_CHECK_CARRIAGE_RETURN : "",
    ERROR_GENERAL_CHECK_FILE_EXISTENCE : "",
    
    ERROR_SPACE_CHECK_ALL : "",
    
    ERROR_PREDICATE_EXPRESSION_CHECK_ALL : "",
    ERROR_PREDICATE_EXPRESSION_CHECK_BOOLEAN_VALUE : "",
    ERROR_PREDICATE_EXPRESSION_CHECK_NO_BOOLEAN_OPERATOR : "",
    ERROR_PREDICATE_EXPRESSION_CHECK_COMPARISON_NULL_TYPE : "",
    
    ERROR_HEADER_CHECK_ALL : "",
    ERROR_HEADER_CHECK_FILE : "",
    ERROR_HEADER_CHECK_FUNCTION : "",
    
    ERROR_C_FUNCTION_LAYOUT_CHECK_ALL : "",
    ERROR_C_FUNCTION_LAYOUT_CHECK_RETURN_TYPE : "",
    ERROR_C_FUNCTION_LAYOUT_CHECK_OPTIONAL_FUNCTIONAL_MODIFIER : "",
    ERROR_C_FUNCTION_LAYOUT_CHECK_FUNCTION_NAME : "",
    ERROR_C_FUNCTION_LAYOUT_CHECK_FUNCTION_PROTO_TYPE : "",
    ERROR_C_FUNCTION_LAYOUT_CHECK_FUNCTION_BODY : "",
    ERROR_C_FUNCTION_LAYOUT_CHECK_DATA_DECLARATION : "",
    ERROR_C_FUNCTION_LAYOUT_CHECK_NO_INIT_OF_VARIABLE : "",
    ERROR_C_FUNCTION_LAYOUT_CHECK_NO_STATIC : "",
    
    ERROR_INCLUDE_FILE_CHECK_ALL : "",
    ERROR_INCLUDE_FILE_CHECK_IFNDEF_STATEMENT : "",
    ERROR_INCLUDE_FILE_CHECK_DATA : "",
    
    ERROR_DECLARATION_DATA_TYPE_CHECK_ALL : "",
    ERROR_DECLARATION_DATA_TYPE_CHECK_NO_USE_C_TYPE : "",
    ERROR_DECLARATION_DATA_TYPE_CHECK_IN_OUT_MODIFIER : "",
    ERROR_DECLARATION_DATA_TYPE_CHECK_EFI_API_MODIFIER : "",
    ERROR_DECLARATION_DATA_TYPE_CHECK_ENUMERATED_TYPE : "",
    ERROR_DECLARATION_DATA_TYPE_CHECK_STRUCTURE_DECLARATION : "",
    ERROR_DECLARATION_DATA_TYPE_CHECK_UNION_TYPE : "",
    
    ERROR_NAMING_CONVENTION_CHECK_ALL : "",
    ERROR_NAMING_CONVENTION_CHECK_DEFINE_STATEMENT : "",
    ERROR_NAMING_CONVENTION_CHECK_TYPEDEF_STATEMENT : "",
    ERROR_NAMING_CONVENTION_CHECK_IFNDEF_STATEMENT : "",
    ERROR_NAMING_CONVENTION_CHECK_PATH_NAME : "",
    ERROR_NAMING_CONVENTION_CHECK_VARIABLE_NAME : "",
    ERROR_NAMING_CONVENTION_CHECK_FUNCTION_NAME : "",
    ERROR_NAMING_CONVENTION_CHECK_SINGLE_CHARACTER_VARIABLE : "",
    
    ERROR_DOXYGEN_CHECK_ALL : "",
    ERROR_DOXYGEN_CHECK_FILE_HEADER : "",
    ERROR_DOXYGEN_CHECK_FUNCTION_HEADER : "",
    ERROR_DOXYGEN_CHECK_COMMENT_DESCRIPTION : "",
    ERROR_DOXYGEN_CHECK_COMMENT_FORMAT : "",
    ERROR_DOXYGEN_CHECK_COMMAND : "",
    
    ERROR_META_DATA_FILE_CHECK_ALL : "",
    ERROR_META_DATA_FILE_CHECK_PATH_NAME : "",
    ERROR_META_DATA_FILE_CHECK_LIBRARY_INSTANCE : "",
    ERROR_META_DATA_FILE_CHECK_LIBRARY_INSTANCE_DEPENDENT : "",
    ERROR_META_DATA_FILE_CHECK_LIBRARY_INSTANCE_ORDER : "",
    ERROR_META_DATA_FILE_CHECK_LIBRARY_NO_USE : "",
    ERROR_META_DATA_FILE_CHECK_BINARY_INF_IN_FDF : "",
    ERROR_META_DATA_FILE_CHECK_PCD_DUPLICATE : "",
    ERROR_META_DATA_FILE_CHECK_PCD_FLASH : "",
    ERROR_META_DATA_FILE_CHECK_PCD_NO_USE : "",
    ERROR_META_DATA_FILE_CHECK_DUPLICATE_GUID : "",
    ERROR_META_DATA_FILE_CHECK_DUPLICATE_PROTOCOL : "",
    ERROR_META_DATA_FILE_CHECK_DUPLICATE_PPI : "",
    
    ERROR_SPELLING_CHECK_ALL : "",
    }