ARCH ?= IA32
MAKEROOT ?= ..

# VPATH = ..

LIBNAME = Common

OBJECTS = CommonLib.o Decompress.o EfiUtilityMsgs.o MyAlloc.o SimpleFileParsing.o Crc32.o EfiCompress.o FvLib.o ParseInf.o TianoCompress.o PeCoffLoaderEx.o BasePeCoff.o

include $(MAKEROOT)/Makefiles/lib.makefile
