!INCLUDE ..\MSmakefile.common

# VPATH = ..

LIBNAME = Common

OBJECTS = CommonLib.obj Decompress.obj EfiUtilityMsgs.obj MyAlloc.obj SimpleFileParsing.obj Crc32.obj EfiCompress.obj FvLib.obj ParseInf.obj TianoCompress.obj

!INCLUDE ..\MSmakefile.lib

