!INCLUDE ..\MSmakefile.common

ARCH = IA32

# VPATH = ..

APPNAME = GuidChk

LIBS = Common.lib String.lib

OBJECTS = FileSearch.obj GuidChk.obj GuidList.obj UtilsMsgs.obj

!INCLUDE ..\MSmakefile.app

