!INCLUDE ..\MSmakefile.common

ARCH = IA32

# VPATH = ..

APPNAME = FlashMap

LIBS = Common.lib String.lib

OBJECTS = FlashDefFile.obj FlashMap.obj Microcode.obj Symbols.obj

!INCLUDE ..\MSmakefile.app

