## @file
# Create makefile for MS nmake and GNU make
#
# Copyright (c) 2007, Intel Corporation
# All rights reserved. This program and the accompanying materials
# are licensed and made available under the terms and conditions of the BSD License
# which accompanies this distribution.  The full text of the license may be found at
# http://opensource.org/licenses/bsd-license.php
#
# THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "AS IS" BASIS,
# WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.
#

## Import Modules
#
import os
import sys
import string
import re
import os.path as path

from Common.EdkIIWorkspaceBuild import *
from Common.EdkIIWorkspace import *
from Common.BuildToolError import *
from Common.Misc import *
from BuildInfo import *
from BuildEngine import *
import Common.GlobalData as GlobalData

## Regular expression for finding header file inclusions
gIncludePattern = re.compile("^[ #]*include[ ]+[\"<]*([^\"< >\s]+)[>\" ]*$", re.MULTILINE | re.UNICODE)

## Regular expression for matching macro used in header file inclusion
gMacroPattern = re.compile("([_A-Z][_A-Z0-9]*)\((.+)\)", re.UNICODE)

##
gProtocolDefinition = "Protocol/%(HeaderKey)s/%(HeaderKey)s.h"
gGuidDefinition = "Guid/%(HeaderKey)s/%(HeaderKey)s.h"
gArchProtocolDefinition = "ArchProtocol/%(HeaderKey)s/%(HeaderKey)s.h"
gPpiDefinition = "Ppi/%(HeaderKey)s/%(HeaderKey)s.h"
gIncludeMacroConversion = {
  "EFI_PROTOCOL_DEFINITION"         :   gProtocolDefinition,
  "EFI_GUID_DEFINITION"             :   gGuidDefinition,
  "EFI_ARCH_PROTOCOL_DEFINITION"    :   gArchProtocolDefinition,
  "EFI_PROTOCOL_PRODUCER"           :   gProtocolDefinition,
  "EFI_PROTOCOL_CONSUMER"           :   gProtocolDefinition,
  "EFI_PROTOCOL_DEPENDENCY"         :   gProtocolDefinition,
  "EFI_ARCH_PROTOCOL_PRODUCER"      :   gArchProtocolDefinition,
  "EFI_ARCH_PROTOCOL_CONSUMER"      :   gArchProtocolDefinition,
  "EFI_ARCH_PROTOCOL_DEPENDENCY"    :   gArchProtocolDefinition,
  "EFI_PPI_DEFINITION"              :   gPpiDefinition,
  "EFI_PPI_PRODUCER"                :   gPpiDefinition,
  "EFI_PPI_CONSUMER"                :   gPpiDefinition,
  "EFI_PPI_DEPENDENCY"              :   gPpiDefinition,
}

gMakefileHeader = '''#
# DO NOT EDIT
# This file is auto-generated by build utility
#
# Module Name:
#
#   %s
#
# Abstract:
#
#   Auto-generated makefile for building modules and libraries
#
'''

gLibraryMakeCommand = '''cd %(makedir)s && "$(MAKE)" $(MAKE_FLAGS) %(target)s
\tcd $(MODULE_BUILD_DIR)'''

gMakeType = ""
if sys.platform == "win32":
    gMakeType = "nmake"
else:
    gMakeType = "gmake"

gMakefileName = {"nmake" : "Makefile", "gmake" : "GNUmakefile"}

gDirectorySeparator = {"nmake" : "\\", "gmake" : "/"}

gCreateDirectoryCommand = {"nmake" : "mkdir", "gmake" : "mkdir -p"}
gRemoveDirectoryCommand = {"nmake" : "rmdir /s /q", "gmake" : "rm -r -f"}
gRemoveFileCommand = {"nmake" : "del /f /q", "gmake" : "rm -f"}
gCopyFileCommand = {"nmake" : "copy /y", "gmake" : "cp -f"}
gCreateDirectoryCommandTemplate = {"nmake" : 'if not exist %(dir)s mkdir %(dir)s',
                                   "gmake" : "test ! -e %(dir)s && mkdir -p %(dir)s"}
gRemoveDirectoryCommandTemplate = {"nmake" : 'if exist %(dir)s rmdir /s /q %(dir)s',
                                   "gmake" : "test -e %(dir)s && rm -r -f %(dir)s"}

#   $(CP)     copy file command
#   $(MV)     move file command
#   $(RM)     remove file command
#   $(MD)     create dir command
#   $(RD)     remove dir command
#
#   $(TCP)     copy file if destination file doesn't exist
#   $(TMV)     move file if destination file doesn't exist
#   $(TRM)     remove file if destination file exists
#   $(TMD)     create dir if destination dir doesn't exist
#   $(TRD)     remove dir if destination dir exists
gShellCommand = {
    "nmake" : {
        "CP"    :   "copy /y",
        "MV"    :   "move /y",
        "RM"    :   "del /f /q",
        "MD"    :   "mkdir",
        "RD"    :   "rmdir /s /q",
    },

    "gmake" : {
        "CP"    :   "cp -f",
        "MV"    :   "mv -f",
        "RM"    :   "rm -f",
        "MD"    :   "mkdir -p",
        "RD"    :   "rm -r -f",
    }
}
gIncludeFlag = {"MSFT" : "/I", "GCC" : "-I", "INTEL" : "-I"}

gStartGroupFlag = {"MSFT" : "", "GCC" : "-(", "INTEL" : ""}
gEndGroupFlag = {"MSFT" : "", "GCC" : "-)", "INTEL" : ""}

gCustomMakefileTemplate = '''\
${makefile_header}

#
# Platform Macro Definition
#
PLATFORM_NAME = ${platform_name}
PLATFORM_GUID = ${platform_guid}
PLATFORM_VERSION = ${platform_version}
PLATFORM_RELATIVE_DIR = ${platform_relative_directory}
PLATFORM_DIR = $(WORKSPACE)${separator}${platform_relative_directory}
PLATFORM_OUTPUT_DIR = ${platform_output_directory}

#
# Module Macro Definition
#
MODULE_NAME = ${module_name}
MODULE_GUID = ${module_guid}
MODULE_VERSION = ${module_version}
MODULE_TYPE = ${module_type}
MODULE_FILE_BASE_NAME = ${module_file_base_name}
BASE_NAME = $(MODULE_NAME)
MODULE_RELATIVE_DIR = ${module_relative_directory}
MODULE_DIR = $(WORKSPACE)${separator}${module_relative_directory}

#
# Build Configuration Macro Definition
#
ARCH = ${architecture}
TOOLCHAIN_TAG = ${toolchain_tag}
TARGET = ${build_target}

#
# Build Directory Macro Definition
#
# PLATFORM_BUILD_DIR = ${platform_build_directory}
BUILD_DIR = ${platform_build_directory}
BIN_DIR = $(BUILD_DIR)${separator}${architecture}
LIB_DIR = $(BIN_DIR)
MODULE_BUILD_DIR = $(BUILD_DIR)${separator}${architecture}${separator}${module_relative_directory}${separator}${module_file_base_name}
OUTPUT_DIR = $(MODULE_BUILD_DIR)${separator}OUTPUT
DEBUG_DIR = $(MODULE_BUILD_DIR)${separator}DEBUG
DEST_DIR_OUTPUT = $(OUTPUT_DIR)
DEST_DIR_DEBUG = $(DEBUG_DIR)

#
# Default Tools Flags Macro Definition (from tools_def.txt by default)
#
${BEGIN}DEFAULT_${tool_code}_FLAGS = ${default_tool_flags}
${END}

#
# Platform Tools Flags Macro Definition (from platform description file)
#
${BEGIN}PLATFORM_${tool_code}_FLAGS = ${platform_tool_flags}
${END}

#
# Platform Tools Flags Macro Definition (from platform description file)
#
${BEGIN}MODULE_${tool_code}_FLAGS = ${module_tool_flags}
${END}

#
# ToolsFlagMacro
#
${BEGIN}${tool_code}_FLAGS = $(DEFAULT_${tool_code}_FLAGS) $(PLATFORM_${tool_code}_FLAGS) $(MODULE_${tool_code}_FLAGS)
${END}

#
# ToolsPathMacro
#
${BEGIN}${tool_code} = ${tool_path}
${END}

${custom_makefile_content}

#
# Target used when called from platform makefile, which will bypass the build of dependent libraries
#

pbuild: init all


#
# Target used for library build, which will bypass the build of dependent libraries
#

lbuild: init all


#
# ModuleTarget
#

mbuild: init all


#
# Initialization target: print build information and create necessary directories
#
init:
\t-@echo Building ... $(MODULE_NAME) $(MODULE_VERSION) [$(ARCH)] in platform $(PLATFORM_NAME) $(PLATFORM_VERSION)
\t${BEGIN}-@${create_directory_command}
\t${END}

'''

gModuleMakefileTemplate = '''\
${makefile_header}

#
# Platform Macro Definition
#
PLATFORM_NAME = ${platform_name}
PLATFORM_GUID = ${platform_guid}
PLATFORM_VERSION = ${platform_version}
PLATFORM_RELATIVE_DIR = ${platform_relative_directory}
PLATFORM_DIR = $(WORKSPACE)${separator}${platform_relative_directory}
PLATFORM_OUTPUT_DIR = ${platform_output_directory}

#
# Module Macro Definition
#
MODULE_NAME = ${module_name}
MODULE_GUID = ${module_guid}
MODULE_VERSION = ${module_version}
MODULE_TYPE = ${module_type}
MODULE_FILE_BASE_NAME = ${module_file_base_name}
BASE_NAME = $(MODULE_NAME)
MODULE_RELATIVE_DIR = ${module_relative_directory}
MODULE_DIR = $(WORKSPACE)${separator}${module_relative_directory}

#
# Build Configuration Macro Definition
#
ARCH = ${architecture}
TOOLCHAIN_TAG = ${toolchain_tag}
TARGET = ${build_target}

#
# Build Directory Macro Definition
#
# PLATFORM_BUILD_DIR = ${platform_build_directory}
BUILD_DIR = ${platform_build_directory}
BIN_DIR = $(BUILD_DIR)${separator}${architecture}
LIB_DIR = $(BIN_DIR)
MODULE_BUILD_DIR = $(BUILD_DIR)${separator}${architecture}${separator}${module_relative_directory}${separator}${module_file_base_name}
OUTPUT_DIR = $(MODULE_BUILD_DIR)${separator}OUTPUT
DEBUG_DIR = $(MODULE_BUILD_DIR)${separator}DEBUG
DEST_DIR_OUTPUT = $(OUTPUT_DIR)
DEST_DIR_DEBUG = $(DEBUG_DIR)

#
# Default Tools Flags Macro Definition (from tools_def.txt by default)
#
${BEGIN}DEFAULT_${tool_code}_FLAGS = ${default_tool_flags}
${END}

#
# Platform Tools Flags Macro Definition (from platform description file)
#
${BEGIN}PLATFORM_${tool_code}_FLAGS = ${platform_tool_flags}
${END}

#
# Module Tools Flags Macro Definition (from platform/module description file)
#
${BEGIN}MODULE_${tool_code}_FLAGS = ${module_tool_flags}
${END}

#
# Tools Flag Macro
#
${BEGIN}${tool_code}_FLAGS = $(DEFAULT_${tool_code}_FLAGS) $(PLATFORM_${tool_code}_FLAGS) $(MODULE_${tool_code}_FLAGS)
${END}

#
# Tools Path Macro
#
${BEGIN}${tool_code} = ${tool_path}
${END}

MAKE_FILE = ${makefile_path}

#
# Shell Command Macro
#
${BEGIN}${shell_command_code} = ${shell_command}
${END}

#
# Build Macro
#
${BEGIN}${source_file_macro}
${END}

${BEGIN}${target_file_macro}
${END}

SOURCE_FILES = ${BEGIN}${source_file_macro_name} ${END}

TARGET_FILES = ${BEGIN}${target_file_macro_name} ${END}

INC = ${BEGIN}${include_path_prefix}${include_path} \\
      ${END}

#OBJECTS = ${BEGIN}$(OUTPUT_DIR)${separator}${object_file} \\
#          ${END}

LIBS = ${BEGIN}$(BUILD_DIR)${separator}$(ARCH)${separator}${library_file} \\
       ${END}${BEGIN}${system_library} \\
       ${END} \\
       $(LIB_LIST)

COMMON_DEPS = ${BEGIN}${common_dependency_file} \\
              ${END}

IMAGE_ENTRY_POINT = ${module_entry_point}
ENTRYPOINT = ${module_entry_point}

#
# Overridable Target Macro Definitions
#
INIT_TARGET = init
PCH_TARGET =
CODA_TARGET = ${BEGIN}${remaining_build_target} \\
              ${END}

#
# Default target, which will build dependent libraries in addition to source files
#

all: ${build_type}


#
# Target used when called from platform makefile, which will bypass the build of dependent libraries
#

pbuild: $(INIT_TARGET) $(PCH_TARGET) $(CODA_TARGET)

#
# ModuleTarget
#

mbuild: $(INIT_TARGET) gen_libs $(PCH_TARGET) $(CODA_TARGET)


#
# Target to update the FD
#

fds: mbuild gen_fds

#
# Initialization target: print build information and create necessary directories
#
init:
\t-@echo Building ... $(MODULE_NAME) $(MODULE_VERSION) [$(ARCH)] in platform $(PLATFORM_NAME) $(PLATFORM_VERSION)
${BEGIN}\t-@${create_directory_command}\n${END}\
${BEGIN}\t-@${copy_autogen_h}\n${END}

#
# GenLibsTarget
#
gen_libs:
\t${BEGIN}cd $(BUILD_DIR)${separator}$(ARCH)${separator}${dependent_library_build_directory} && "$(MAKE)" $(MAKE_FLAGS)
\t${END}cd $(MODULE_BUILD_DIR)

#
# Build Flash Device Image
#
gen_fds:
\tcd $(BUILD_DIR) && "$(MAKE)" $(MAKE_FLAGS) fds
\tcd $(MODULE_BUILD_DIR)

#
# Individual Object Build Targets
#
${BEGIN}${file_build_target}
${END}


#
# clean all intermediate files
#

clean:
\t${BEGIN}${clean_command}
\t${END}

#
# clean all generated files
#

cleanall:
${BEGIN}\t${cleanall_command}
${END}\t$(RM) *.pdb *.idb > NUL 2>&1
\t$(RM) $(BIN_DIR)${separator}$(MODULE_NAME).efi

#
# clean pre-compiled header files
#

cleanpch:
\t$(RM) $(OUTPUT_DIR)\*.pch > NUL 2>&1

#
# clean all dependent libraries built
#

cleanlib:
\t${BEGIN}cd $(BUILD_DIR)${separator}$(ARCH)${separator}${dependent_library_build_directory} && "$(MAKE)" $(MAKE_FLAGS) cleanall
\t${END}cd $(MODULE_BUILD_DIR)

'''

gPlatformMakefileTemplate = '''\
${makefile_header}

#
# Platform Macro Definition
#
PLATFORM_NAME = ${platform_name}
PLATFORM_GUID = ${platform_guid}
PLATFORM_VERSION = ${platform_version}
PLATFORM_DIR = $(WORKSPACE)${separator}${platform_relative_directory}
PLATFORM_OUTPUT_DIR = ${platform_output_directory}

#
# Build Configuration Macro Definition
#
TOOLCHAIN_TAG = ${toolchain_tag}
TARGET = ${build_target}

#
# Build Directory Macro Definition
#
BUILD_DIR = ${platform_build_directory}
FV_DIR = ${platform_build_directory}${separator}FV

#
# Shell Command Macro
#
${BEGIN}${shell_command_code} = ${shell_command}
${END}

MAKE = ${make_path}
MAKE_FLAGS = ${make_flag}
MAKE_FILE = ${makefile_path}

#
# Default target
#
all: init build_libraries build_modules build_fds

#
# Initialization target: print build information and create necessary directories
#
init:
\t-@echo Building ... $(PLATFORM_NAME) $(PLATFORM_VERSION) [${build_architecture_list}]
\t${BEGIN}-@${create_directory_command}
\t${END}
#
# library build target
#
libraries: init build_libraries

#
# module build target
#
modules: init build_libraries build_modules

#
# Flash Device Image Target
#
fds: init build_fds

#
# Build all libraries:
#
build_libraries:
${BEGIN}\tcd ${library_build_directory} && "$(MAKE)" $(MAKE_FLAGS) pbuild
${END}\tcd $(BUILD_DIR)

#
# Build all modules:
#
build_modules:
${BEGIN}\tcd ${module_build_directory} && "$(MAKE)" $(MAKE_FLAGS) pbuild
${END}\tcd $(BUILD_DIR)

#
# Build Flash Device Image
#
build_fds:
\t-@cd $(FV_DIR)
${BEGIN}\tGenFds -f ${fdf_file} -o $(BUILD_DIR) -t $(TOOLCHAIN_TAG) -b $(TARGET) -p ${active_platform} -a ${build_architecture_list} ${log_level}${END}${BEGIN} -r ${fd} ${END}${BEGIN} -i ${fv} ${END}${BEGIN} -y ${macro} ${END}

#
# run command for emulator platform only
#
run:
\tcd $(BUILD_DIR)${separator}IA32
\tSecMain
\tcd $(BUILD_DIR)

#
# Clean intermediate files
#
clean:
\t${BEGIN}cd ${library_build_directory} && "$(MAKE)" $(MAKE_FLAGS) clean
\t${END}${BEGIN}cd ${module_build_directory} && "$(MAKE)" $(MAKE_FLAGS) clean
\t${END}cd $(BUILD_DIR)

#
# Clean all generated files except to makefile
#
cleanall:
${BEGIN}\t${cleanall_command}
${END}

#
# Clean all library files
#
cleanlib:
\t${BEGIN}cd ${library_build_directory} && "$(MAKE)" $(MAKE_FLAGS) cleanall
\t${END}cd $(BUILD_DIR)

'''

## Makefile class
#
#  This class encapsules makefie and its generation. It uses template to generate
#  the content of makefile. The content of makefile will be got from PlatformBuildInfo
#  or ModuleBuildInfo objects.
#
class Makefile(object):
    ## Constructor
    #
    #  Intitialize the data member simply
    #
    #   @param      Info    PlatformBuildInfo or ModuleBuildInfo object
    #   @param      Option  Option for the makefile generation (not used)
    #
    def __init__(self, Info, Option=None):
        if isinstance(Info, ModuleBuildInfo):
            if Info == None or Info == "":
                EdkLogger.error("AutoGen", AUTOGEN_ERROR, "No valid module found! Please check your build configuration!\n")
            self.ModuleInfo = Info
            self.PlatformInfo = Info.PlatformInfo
            self.ModuleBuild = True

            self.BuildType = "mbuild"
            self.TargetFileList = []
            self.ObjectFileList = []

            self.ResultFileList = []
            self.IntermediateDirectoryList = ["$(DEBUG_DIR)", "$(OUTPUT_DIR)"]
        
            self.SourceFileDatabase = {}  # {file type : file path}
            self.DestFileDatabase = {}  # {file type : file path}
            self.FileBuildTargetList = [] # [(src, target string)]
            self.BuildTargetList = [] # [target string]
            self.PendingBuildTargetList = [] # [FileBuildRule objects]
            self.CommonFileDependency = []

            self.FileDependency = []
            self.LibraryBuildCommandList = []
            self.LibraryFileList = []
            self.LibraryMakefileList = []
            self.LibraryBuildDirectoryList = []
            self.SystemLibraryList = []
        elif type(Info) == type({}):    # and isinstance(info, PlatformBuildInfo):
            if len(Info) <= 0:
                EdkLogger.error("AutoGen", AUTOGEN_ERROR, "No buildable platform found! Please check your build configuration!\n")
            self.PlatformInfo = Info
            self.ModuleBuild = False
            self.ModuleBuildCommandList = []
            self.ModuleMakefileList = []
            self.ModuleBuildDirectoryList = self.GetModuleBuildDirectoryList()
            self.LibraryBuildDirectoryList = self.GetLibraryBuildDirectoryList()
        else:
            EdkLogger.error("AutoGen", AUTOGEN_ERROR, "Non-buildable item:%s" % str(Info))

        self.IntermediateDirectoryList = []

    ## Create necessary directory for makefile generation
    def PrepareDirectory(self):
        if self.ModuleBuild:
            CreateDirectory(self.PlatformInfo.BuildDir)
            CreateDirectory(self.ModuleInfo.BuildDir)
            CreateDirectory(self.ModuleInfo.DebugDir)

    ## Create the makefile
    #
    #   @param      File        The path of the makefile
    #   @param      MakeType    GNU makefile or MS makefile
    #
    #   @retval     True        If the file is changed or doesn't exist
    #   @retval     False       If the file exists and its content is not changed
    #                           since last time
    #
    def Generate(self, File=None, MakeType=gMakeType):
        if self.ModuleBuild:
            return self.GenerateModuleMakefile(File, MakeType)
        else:
            return self.GeneratePlatformMakefile(File, MakeType)

    ## Create makefile of platform
    #
    #   @param      File        The path of the makefile
    #   @param      MakeType    GNU makefile or MS makefile
    #
    #   @retval     True        If the file is changed or doesn't exist
    #   @retval     False       If the file exists and its content is not changed
    #                           since last time
    #
    def GeneratePlatformMakefile(self, File=None, MakeType=gMakeType):
        Separator = gDirectorySeparator[MakeType]

        ArchList = self.PlatformInfo.keys()
        PlatformInfo = self.PlatformInfo.values()[0]
        ActivePlatform = PlatformInfo.Platform

        if "MAKE" not in PlatformInfo.ToolPath:
            EdkLogger.error("GenMake", OPTION_MISSING, "No MAKE command defined. Please check your tools_def.txt!")

        self.IntermediateDirectoryList = ["$(BUILD_DIR)%s%s" % (Separator, Arch) for Arch in self.PlatformInfo]
        self.IntermediateDirectoryList.append("$(FV_DIR)")

        # TRICK: for not generating GenFds call in makefile if no FDF file
        MacroList = []
        if PlatformInfo.FdfFile != None and PlatformInfo.FdfFile != "":
            FdfFileList = [PlatformInfo.FdfFile]
            for MacroName in GlobalData.gGlobalDefines:
                MacroList.append('"%s=%s"' % (MacroName, GlobalData.gGlobalDefines[MacroName]))    
        else:
            FdfFileList = []

        # pass log level to external program called in makefile, currently GenFds.exe
        LogLevel = EdkLogger.GetLevel()
        if LogLevel == EdkLogger.VERBOSE:
            LogOption = "-v"
        elif LogLevel <= EdkLogger.DEBUG_9:
            LogOption = "-d %d" % (LogLevel - 1)
        elif LogLevel == EdkLogger.QUIET:
            LogOption = "-q"
        else:
            LogOption = ""

        MakefileName = gMakefileName[MakeType]
        MakefileTemplateDict = {
            "makefile_header"           : gMakefileHeader % MakefileName,
            "makefile_path"             : os.path.join("$(BUILD_DIR)", MakefileName),
            "platform_name"             : PlatformInfo.Name,
            "platform_guid"             : PlatformInfo.Guid,
            "platform_version"          : PlatformInfo.Version,
            "platform_relative_directory": PlatformInfo.SourceDir,
            "platform_output_directory" : PlatformInfo.OutputDir,
            "platform_build_directory"  : PlatformInfo.BuildDir,

            "toolchain_tag"             : PlatformInfo.ToolChain,
            "build_target"              : PlatformInfo.BuildTarget,
            "make_path"                 : PlatformInfo.ToolPath["MAKE"],
            "make_flag"                 : PlatformInfo.ToolOption["MAKE"],
            "shell_command_code"        : gShellCommand[MakeType].keys(),
            "shell_command"             : gShellCommand[MakeType].values(),
            "build_architecture_list"   : ",".join(ArchList),
            "architecture"              : self.PlatformInfo.keys(),
            "separator"                 : Separator,
            "create_directory_command"  : self.GetCreateDirectoryCommand(self.IntermediateDirectoryList, MakeType),
            "remove_directory_command"  : gRemoveDirectoryCommand[MakeType],
            "remove_file_command"       : gRemoveFileCommand[MakeType],
            "cleanall_command"          : self.GetRemoveDirectoryCommand(self.IntermediateDirectoryList, MakeType),
            "library_build_directory"   : self.LibraryBuildDirectoryList,
            "module_build_directory"    : self.ModuleBuildDirectoryList,
            "fdf_file"                  : FdfFileList,
            "active_platform"           : PlatformInfo.WorkspaceDir + Separator + ActivePlatform.DescFilePath,
            "fd"                        : PlatformInfo.FdTargetList,
            "fv"                        : PlatformInfo.FvTargetList,
            "log_level"                 : LogOption,
            "macro"                     : MacroList,
        }

        self.PrepareDirectory()

        AutoGenMakefile = TemplateString()
        AutoGenMakefile.Append(gPlatformMakefileTemplate, MakefileTemplateDict)

        FilePath = ""
        if File == None:
            os.chdir(PlatformInfo.MakeFileDir)
            FilePath = MakefileName
        else:
            FilePath = File

        Result = SaveFileOnChange(FilePath, str(AutoGenMakefile))
        os.chdir(PlatformInfo.WorkspaceDir)
        return Result

    ## Create makefile of a module
    #
    #   @param      File        The path of the makefile
    #   @param      MakeType    GNU makefile or MS makefile
    #
    #   @retval     True        If the file is changed or doesn't exist
    #   @retval     False       If the file exists and its content is not changed
    #                           since last time
    #
    def GenerateModuleMakefile(self, File=None, MakeType=gMakeType):
        if MakeType in self.ModuleInfo.CustomMakefile and self.ModuleInfo.CustomMakefile[MakeType] != "":
            return self.GenerateCustomBuildMakefile(File, MakeType)

        Separator = gDirectorySeparator[MakeType]
        PlatformInfo = self.PlatformInfo

        # break build if no source files and binary files are found
        if len(self.ModuleInfo.SourceFileList) == 0 and len(self.ModuleInfo.BinaryFileDict) == 0:
            EdkLogger.error("AutoGen", AUTOGEN_ERROR, "No files to be built in module [%s, %s, %s]"
                            % (self.ModuleInfo.BuildTarget, self.ModuleInfo.ToolChain, self.ModuleInfo.Arch),
                            ExtraData=str(self.ModuleInfo.Module))
        # convert source files and binary files to build target
        if len(self.ModuleInfo.SourceFileList) > 0:
            self.ProcessSourceFileList(MakeType)
        if len(self.ModuleInfo.BinaryFileDict) > 0:
            self.ProcessBinaryFileList(MakeType)
        # convert dependent libaries to build command
        self.ProcessDependentLibrary(MakeType)

        if "DLINK" in PlatformInfo.ToolStaticLib:
            EdkLogger.debug(EdkLogger.DEBUG_5, "Static library: " + PlatformInfo.ToolStaticLib["DLINK"])
            self.SystemLibraryList.append(PlatformInfo.ToolStaticLib["DLINK"])

        if self.ModuleInfo.Arch == "EBC":
            # EBC compiler always use "EfiStart" as entry point
            EntryPoint = "EfiStart"
        elif self.ModuleInfo.AutoGenVersion < 0x00010005 and len(self.ModuleInfo.Module.ModuleEntryPointList) > 0:
            # R8 modules use different entry point functions
            EntryPoint = self.ModuleInfo.Module.ModuleEntryPointList[0]
        else:
            # R9 modules always use "_ModuleEntryPoint" as entry point
            EntryPoint = "_ModuleEntryPoint"

        DefaultToolFlag = PlatformInfo.ToolOption.values()
        if self.ModuleInfo.ModuleType == "USER_DEFINED":
            DefaultToolFlag = ["" for p in DefaultToolFlag]

        if "CC" not in PlatformInfo.ToolChainFamily:
            EdkLogger.error("AutoGen", AUTOGEN_ERROR, "Tool [CC] is not supported [%s, %s, %s]" % (self.ModuleInfo.BuildTarget,
                                    self.ModuleInfo.ToolChain, self.ModuleInfo.Arch))
        if  "DLINK" not in PlatformInfo.ToolChainFamily:
            EdkLogger.error("AutoGen", AUTOGEN_ERROR, "Tool [DLINK] is not supported [%s, %s, %s]" % (self.ModuleInfo.BuildTarget,
                                    self.ModuleInfo.ToolChain, self.ModuleInfo.Arch))

        if self.ModuleInfo.IsLibrary:
            if "Static-Library-File" in self.DestFileDatabase:
                self.ResultFileList = self.DestFileDatabase["Static-Library-File"]
        elif self.ModuleInfo.ModuleType == "USER_DEFINED":
            if "Dynamic-Library-File" in self.DestFileDatabase:
                self.ResultFileList = self.DestFileDatabase["Dynamic-Library-File"]
        if len(self.ResultFileList) == 0:
            EdkLogger.error("AutoGen", AUTOGEN_ERROR, "Don't know how to end the module build")

        SourceFileMacroNameList = []
        SourceFileMacroList = [] # macro name = file list
        for FileType in self.SourceFileDatabase:
            Macro = "%s_LIST" % FileType.replace("-", "_").upper()
            SourceFileMacroNameList.append("$(%s)" % Macro)
            Template = TemplateString()
            Template.Append("%s = ${BEGIN}${source_file} \\\n\t${END}" % Macro,
                            {"source_file" : self.SourceFileDatabase[FileType]})
            SourceFileMacroList.append(str(Template))
        TargetFileMacroList = []
        TargetFileMacroNameList = []
        for FileType in self.DestFileDatabase:
            Macro = "%s_LIST" % FileType.replace("-", "_").upper()
            TargetFileMacroNameList.append("$(%s)" % Macro)
            Template = TemplateString()
            Template.Append("%s = ${BEGIN}${target_file} \\\n\t${END}" % Macro,
                            {"target_file" : self.DestFileDatabase[FileType]})
            TargetFileMacroList.append(str(Template))

        # R8 modules need <BaseName>StrDefs.h for string ID
        if self.ModuleInfo.AutoGenVersion < 0x00010005 and len(self.ModuleInfo.UnicodeFileList) > 0:
            AutoGenHeaderFile = os.path.join("$(DEBUG_DIR)", "AutoGen.h")
            StringHeaderFile = os.path.join("$(DEBUG_DIR)", "%sStrDefs.h" % self.ModuleInfo.BaseName)
            CopyAutoGenHeaderFile = ["$(CP) %s %s" % (AutoGenHeaderFile, StringHeaderFile)]
        else:
            CopyAutoGenHeaderFile = []

        MakefileName = gMakefileName[MakeType]
        MakefileTemplateDict = {
            "makefile_header"           : gMakefileHeader % MakefileName,
            "makefile_path"             : os.path.join("$(MODULE_BUILD_DIR)", MakefileName),
            "platform_name"             : PlatformInfo.Name,
            "platform_guid"             : PlatformInfo.Guid,
            "platform_version"          : PlatformInfo.Version,
            "platform_relative_directory": PlatformInfo.SourceDir,
            "platform_output_directory" : PlatformInfo.OutputDir,

            "module_name"               : self.ModuleInfo.Name,
            "module_guid"               : self.ModuleInfo.Guid,
            "module_version"            : self.ModuleInfo.Version,
            "module_type"               : self.ModuleInfo.ModuleType,
            "module_file_base_name"     : self.ModuleInfo.FileBase,
            "module_relative_directory" : self.ModuleInfo.SourceDir,

            "architecture"              : self.ModuleInfo.Arch,
            "toolchain_tag"             : self.ModuleInfo.ToolChain,
            "build_target"              : self.ModuleInfo.BuildTarget,

            "platform_build_directory"  : PlatformInfo.BuildDir,

            "separator"                 : Separator,
            "default_tool_flags"        : DefaultToolFlag,
            "platform_tool_flags"       : [PlatformInfo.BuildOption[tool] for tool in PlatformInfo.ToolPath],
            "module_tool_flags"         : [self.ModuleInfo.BuildOption[tool] for tool in PlatformInfo.ToolPath],

            "tool_code"                 : PlatformInfo.ToolPath.keys(),
            "tool_path"                 : PlatformInfo.ToolPath.values(),

            "shell_command_code"        : gShellCommand[MakeType].keys(),
            "shell_command"             : gShellCommand[MakeType].values(),

            "module_entry_point"        : EntryPoint,
            "include_path_prefix"       : gIncludeFlag[PlatformInfo.ToolChainFamily["CC"]],
            "dlink_output_flag"         : PlatformInfo.OutputFlag["DLINK"],
            "slink_output_flag"         : PlatformInfo.OutputFlag["SLINK"],
            "start_group_flag"          : gStartGroupFlag[PlatformInfo.ToolChainFamily["DLINK"]],
            "end_group_flag"            : gEndGroupFlag[PlatformInfo.ToolChainFamily["DLINK"]],
            "include_path"              : self.ModuleInfo.IncludePathList,
            #"target_file"               : self.TargetFileList,
            #"object_file"               : self.ObjectFileList,
            "library_file"              : self.LibraryFileList,
            "remaining_build_target"    : self.ResultFileList,
            "system_library"            : self.SystemLibraryList,
            "common_dependency_file"    : self.CommonFileDependency,
            "create_directory_command"  : self.GetCreateDirectoryCommand(self.IntermediateDirectoryList, MakeType),
            "remove_directory_command"  : gRemoveDirectoryCommand[MakeType],
            "remove_file_command"       : gRemoveFileCommand[MakeType],
            "copy_file_command"         : gCopyFileCommand[MakeType],
            "clean_command"             : self.GetRemoveDirectoryCommand(["$(OUTPUT_DIR)"], MakeType),
            "cleanall_command"          : self.GetRemoveDirectoryCommand(["$(DEBUG_DIR)", "$(OUTPUT_DIR)"], MakeType),
            "dependent_library_build_directory" : self.LibraryBuildDirectoryList,
            "build_type"                        : self.BuildType,
            "source_file_macro"         : SourceFileMacroList,
            "target_file_macro"         : TargetFileMacroList,
            "source_file_macro_name"    : SourceFileMacroNameList,
            "target_file_macro_name"    : TargetFileMacroNameList,
            "file_build_target"         : self.BuildTargetList,
            "copy_autogen_h"            : CopyAutoGenHeaderFile,
        }

        self.PrepareDirectory()

        AutoGenMakefile = TemplateString()
        AutoGenMakefile.Append(gModuleMakefileTemplate, MakefileTemplateDict)

        FilePath = ""
        if File == None:
            os.chdir(self.ModuleInfo.PlatformInfo.BuildDir)
            os.chdir(self.ModuleInfo.MakeFileDir)
            FilePath = MakefileName
        else:
            FilePath = File

        Result = SaveFileOnChange(FilePath, str(AutoGenMakefile))
        os.chdir(self.ModuleInfo.WorkspaceDir)
        return Result

    ## Create customized makefile for a module
    #
    #   @param      File        The path of the makefile
    #   @param      MakeType    GNU makefile or MS makefile
    #
    #   @retval     True        If the file is changed or doesn't exist
    #   @retval     False       If the file exists and its content is not changed
    #                           since last time
    #
    def GenerateCustomBuildMakefile(self, File=None, MakeType=gMakeType):
        Separator = gDirectorySeparator[MakeType]
        CustomMakefile = open(os.path.join(self.ModuleInfo.WorkspaceDir, self .ModuleInfo.CustomMakefile[MakeType]), 'r').read()

        MakefileName = gMakefileName[MakeType]
        MakefileTemplateDict = {
            "makefile_header"           : gMakefileHeader % MakefileName,
            "platform_name"             : self.PlatformInfo.Name,
            "platform_guid"             : self.PlatformInfo.Guid,
            "platform_version"          : self.PlatformInfo.Version,
            "platform_relative_directory": self.PlatformInfo.SourceDir,
            "platform_output_directory" : self.PlatformInfo.OutputDir,

            "module_name"               : self.ModuleInfo.Name,
            "module_guid"               : self.ModuleInfo.Guid,
            "module_version"            : self.ModuleInfo.Version,
            "module_type"               : self.ModuleInfo.ModuleType,
            "module_file_base_name"     : self.ModuleInfo.FileBase,
            "module_relative_directory" : self.ModuleInfo.SourceDir,

            "architecture"              : self.ModuleInfo.Arch,
            "toolchain_tag"             : self.ModuleInfo.ToolChain,
            "build_target"              : self.ModuleInfo.BuildTarget,

            "platform_build_directory"  : self.PlatformInfo.BuildDir,

            "separator"                 : Separator,
            "default_tool_flags"        : self.PlatformInfo.ToolOption.values(),
            "platform_tool_flags"       : self.PlatformInfo.BuildOption.values(),
            "module_tool_flags"         : self.ModuleInfo.BuildOption.values(),

            "tool_code"                 : self.PlatformInfo.ToolPath.keys(),
            "tool_path"                 : self.PlatformInfo.ToolPath.values(),

            "create_directory_command"  : self.GetCreateDirectoryCommand(self.IntermediateDirectoryList, MakeType),
            "directory_to_be_created"   : self.IntermediateDirectoryList,
            "dependent_library_build_directory" : self.LibraryBuildDirectoryList,
            "custom_makefile_content"   : CustomMakefile
        }

        self.PrepareDirectory()

        AutoGenMakefile = TemplateString()
        AutoGenMakefile.Append(gCustomMakefileTemplate, MakefileTemplateDict)

        FilePath = ""
        if File == None:
            FilePath = path.join(self.ModuleInfo.WorkspaceDir, self.ModuleInfo.MakeFileDir, MakefileName)
        else:
            FilePath = File

        return SaveFileOnChange(FilePath, str(AutoGenMakefile))

    ## Process source files to generate makefile targets and dependencies
    #
    #  The intermediate and final targets and dependencies are controlled by
    #  build rules in $(WORKSPACE)/Conf/build_rule.txt. The dependencies of source
    #  file are figured out by search included files in the source file.
    #
    #   @param      MakeType    GNU makefile or MS makefile
    #
    def ProcessSourceFileList(self, MakeType=gMakeType):
        Separator = gDirectorySeparator[MakeType]

        ForceIncludedFile = []
        SourceFileList = []

        if "CC" not in self.PlatformInfo.ToolChainFamily:
            EdkLogger.error("AutoGen", AUTOGEN_ERROR, "No CC tool found",
                            ExtraData=str(self.ModuleInfo.Module))
        Family = self.PlatformInfo.ToolChainFamily["CC"]
        BuildRule = self.PlatformInfo.BuildRule

        CCodeFlag = False
        FileList = self.ModuleInfo.SourceFileList
        SourceDir = os.path.join(self.ModuleInfo.WorkspaceDir, self.ModuleInfo.SourceDir)
        for FileInfo in FileList:
            F, SrcFileType, SrcFileBuildRule = FileInfo
            if SrcFileType == "C-Code-File":
                CCodeFlag = True
            SrcFileName = path.basename(F)
            SrcFileBase, SrcFileExt = path.splitext(SrcFileName)
            SrcFileDir = path.dirname(F)
            if SrcFileDir == "":
                SrcFileDir = "."
            else:
                P = "$(OUTPUT_DIR)" + Separator + SrcFileDir
                if P not in self.IntermediateDirectoryList:
                    self.IntermediateDirectoryList.append(P)
            SrcFileRelativePath = os.path.join(SourceDir, F)

            SrcFile, ExtraSrcFileList, DstFile, CommandList = SrcFileBuildRule.Apply(F, SourceDir, Separator)
            if SrcFileType not in self.SourceFileDatabase:
                self.SourceFileDatabase[SrcFileType] = []
            self.SourceFileDatabase[SrcFileType].append(SrcFile)
            SourceFileList.append(SrcFileRelativePath)

            BuildTargetTemplate = "${BEGIN}%s : ${deps}\n"\
                                  "${END}\t%s\n" % (DstFile, "\n\t".join(CommandList))
            self.FileBuildTargetList.append((SrcFileRelativePath, BuildTargetTemplate))

            while True:
                # next target
                DstFileType, DstFileBuildRule = BuildRule.Get(SrcFileBuildRule.DestFileExt, Family)
                if DstFileType == None:
                    DstFileType = "Unknown-Type-File"

                if DstFileType  in self.SourceFileDatabase:
                    self.SourceFileDatabase[DstFileType].append(DstFile)
                else:
                    if DstFileType not in self.DestFileDatabase:
                        self.DestFileDatabase[DstFileType] = []
                    self.DestFileDatabase[DstFileType].append(DstFile)

                if DstFileBuildRule != None and DstFileBuildRule.IsMultipleInput:
                    if DstFileBuildRule not in self.PendingBuildTargetList:
                        self.PendingBuildTargetList.append(DstFileBuildRule)
                    break
                elif DstFileBuildRule == None or DstFileBuildRule.CommandList == []:
                    self.ResultFileList.append(DstFile)
                    break

                SrcFile, ExtraSrcFileList, DstFile, CommandList = DstFileBuildRule.Apply(DstFile, None, Separator)
                BuildTargetString = "%s : %s %s\n"\
                                    "\t%s\n" % (DstFile, SrcFile, " ".join(ExtraSrcFileList), "\n\t".join(CommandList))
                self.FileBuildTargetList.append((SrcFile, BuildTargetString))
                SrcFileBuildRule = DstFileBuildRule

        # handle pending targets
        TempBuildTargetList = []
        while True:
            while len(self.PendingBuildTargetList) > 0:
                SrcFileBuildRule = self.PendingBuildTargetList.pop()
                SrcFileList = []
                for FileType in SrcFileBuildRule.SourceFileType:
                    if FileType not in self.SourceFileDatabase:
                        if FileType not in self.DestFileDatabase:
                            continue
                        else:
                            SrcFileList.extend(self.DestFileDatabase[FileType])
                    else:
                        SrcFileList.extend(self.SourceFileDatabase[FileType])
                SrcFile, ExtraSrcFileList, DstFile, CommandList = SrcFileBuildRule.Apply(SrcFileList, None, Separator)
                BuildTargetString = "%s : %s %s\n"\
                                    "\t%s\n" % (DstFile, SrcFile, " ".join(ExtraSrcFileList), "\n\t".join(CommandList))
                self.FileBuildTargetList.append((SrcFile, BuildTargetString))

                # try to find next target
                while True:
                    DstFileType, DstFileBuildRule = BuildRule.Get(SrcFileBuildRule.DestFileExt, Family)
                    if DstFileType == None:
                        DstFileType = "Unknown-Type-File"

                    if DstFileType  in self.SourceFileDatabase:
                        self.SourceFileDatabase[DstFileType].append(DstFile)
                    else:
                        if DstFileType not in self.DestFileDatabase:
                            self.DestFileDatabase[DstFileType] = []
                        self.DestFileDatabase[DstFileType].append(DstFile)

                    if DstFileBuildRule != None and DstFileBuildRule.IsMultipleInput:
                        TempBuildTargetList.append(DstFileBuildRule)
                        break
                    elif DstFileBuildRule == None or DstFileBuildRule.CommandList == []:
                        self.ResultFileList.append(DstFile)
                        break

                    SrcFile, ExtraSrcFileList, DstFile, CommandList = DstFileBuildRule.Apply(DstFile, None, Separator)
                    BuildTargetString = "%s : %s %s\n"\
                                        "\t%s\n" % (DstFile, SrcFile, " ".join(ExtraSrcFileList), "\n\t".join(CommandList))
                    self.FileBuildTargetList.append((SrcFile, BuildTargetString))
                    SrcFileBuildRule = DstFileBuildRule
            if len(TempBuildTargetList) == 0:
                break
            self.PendingBuildTargetList = TempBuildTargetList

        # Build AutoGen files only if we have C source files
        if CCodeFlag == True:
            for F in self.ModuleInfo.AutoGenFileList:
                SrcFileName = path.basename(F)
                SrcFileBase, SrcFileExt = path.splitext(SrcFileName)
                SrcFileDir = path.dirname(F)
                if SrcFileDir == "":
                    SrcFileDir = "."
                else:
                    P = "$(DEBUG_DIR)" + Separator + SrcFileDir
                    if P not in self.IntermediateDirectoryList:
                        self.IntermediateDirectoryList.append(P)

                SrcFileRelativePath = os.path.join(self.ModuleInfo.DebugDir, F)

                SrcFileType, SrcFileBuildRule = BuildRule.Get(SrcFileExt, Family)
                if SrcFileType != None and SrcFileType == "C-Header-File":
                    ForceIncludedFile.append(SrcFileRelativePath)
                if SrcFileBuildRule == None or SrcFileBuildRule.CommandList == []:
                    continue

                SrcFile, ExtraSrcFileList, DstFile, CommandList = SrcFileBuildRule.Apply(F, self.ModuleInfo.DebugDir, Separator)

                if SrcFileType not in self.SourceFileDatabase:
                    self.SourceFileDatabase[SrcFileType] = []
                self.SourceFileDatabase[SrcFileType].append(SrcFile)
                SourceFileList.append(SrcFileRelativePath)

                BuildTargetTemplate = "${BEGIN}%s : ${deps}\n"\
                                      "${END}\t%s\n" % (DstFile, "\n\t".join(CommandList))
                self.FileBuildTargetList.append((SrcFileRelativePath, BuildTargetTemplate))

                while True:
                    # next target
                    DstFileType, DstFileBuildRule = BuildRule.Get(SrcFileBuildRule.DestFileExt, Family)
                    if DstFileType == None:
                        DstFileType = "Unknown-Type-File"

                    if DstFileType  in self.SourceFileDatabase:
                        self.SourceFileDatabase[DstFileType].append(DstFile)
                    else:
                        if DstFileType not in self.DestFileDatabase:
                            self.DestFileDatabase[DstFileType] = []
                        self.DestFileDatabase[DstFileType].append(DstFile)

                    if DstFileBuildRule != None and DstFileBuildRule.IsMultipleInput:
                        if DstFileBuildRule not in self.PendingBuildTargetList:
                            self.PendingBuildTargetList.append(DstFileBuildRule)
                        break
                    elif DstFileBuildRule == None or DstFileBuildRule.CommandList == []:
                        self.ResultFileList.append(DstFile)
                        break

                    SrcFile, ExtraSrcFileList, DstFile, CommandList = DstFileBuildRule.Apply(DstFile, None, Separator)
                    BuildTargetString = "%s : %s %s\n"\
                                        "\t%s\n" % (DstFile, SrcFile, " ".join(ExtraSrcFileList), "\n\t".join(CommandList))
                    self.FileBuildTargetList.append((SrcFile, BuildTargetString))
                    SrcFileBuildRule = DstFileBuildRule

        #
        # Search dependency file list for each source file
        #
        self.FileDependency = self.GetFileDependency(SourceFileList, ForceIncludedFile, self.ModuleInfo.IncludePathList)
        DepSet = None
        for File in self.FileDependency:
            # skip non-C files
            if (not File.endswith(".c") and not File.endswith(".C")) or File.endswith("AutoGen.c"):
                continue
            elif DepSet == None:
                DepSet = set(self.FileDependency[File])
            else:
                DepSet &= set(self.FileDependency[File])
        # in case nothing in SourceFileList
        if DepSet == None:
            DepSet = set()
        #
        # Extract comman files list in the dependency files
        #
        self.CommonFileDependency = list(DepSet)
        for F in self.FileDependency:
            NewDepSet = set(self.FileDependency[F])
            NewDepSet -= DepSet
            if File.endswith(".c") or File.endswith(".C") or not File.endswith("AutoGen.c"):
                self.FileDependency[F] = ["$(COMMON_DEPS)"] + list(NewDepSet)

        for File, TargetTemplate in self.FileBuildTargetList:
            if File not in self.FileDependency:
                self.BuildTargetList.append(TargetTemplate)
                continue
            Template = TemplateString()
            Template.Append(TargetTemplate, {"deps" : self.FileDependency[File]})
            self.BuildTargetList.append(str(Template))


    ## Process binary files to generate makefile targets and dependencies
    #
    # All binary files are just copied to $(OUTPUT_DIR)
    # 
    #   @param      MakeType    GNU makefile or MS makefile
    #
    def ProcessBinaryFileList(self, MakeType=gMakeType):
        BinaryFiles = self.ModuleInfo.BinaryFileDict
        BuildTargetString = "%(dst)s : %(src)s\n"\
                            "\t$(CP) %(src)s %(dst)s\n"
        for FileType in BinaryFiles:
            if FileType not in self.DestFileDatabase:
                self.DestFileDatabase[FileType] = []
            for F in BinaryFiles[FileType]:
                Src = os.path.join("$(MODULE_DIR)", F)
                FileName = os.path.basename(F)
                Dst = os.path.join("$(OUTPUT_DIR)", FileName)
                self.DestFileDatabase[FileType].append(Dst)
                self.ResultFileList.append(Dst)
                self.BuildTargetList.append(BuildTargetString % {"dst":Dst, "src":Src})

    ## For creating makefile targets for dependent libraries
    #
    #   @param      MakeType    GNU makefile or MS makefile
    #
    def ProcessDependentLibrary(self, MakeType=gMakeType):
        for LibraryModule in self.ModuleInfo.DependentLibraryList:
            LibraryFile = str(LibraryModule)
            FileBase = path.basename(LibraryFile).split(".")[0]
            LibraryBuildPath = path.dirname(LibraryFile) + gDirectorySeparator[MakeType] + FileBase
            self.LibraryBuildDirectoryList.append(LibraryBuildPath)
            self.LibraryFileList.append(gDirectorySeparator[MakeType].join([LibraryBuildPath, "OUTPUT", LibraryModule.BaseName + ".lib"]))

    ## Determine the root directory for a platform build
    def GetPlatformBuildDirectory(self):
        return self.PlatformInfo.BuildDir

    ## Return a list containing source file's dependencies
    #
    #   @param      FileList        The list of source files
    #   @param      ForceInculeList The list of files which will be included forcely
    #   @param      SearchPathList  The list of search path
    #
    #   @retval     dict            The mapping between source file path and its dependencies
    #
    def GetFileDependency(self, FileList, ForceInculeList, SearchPathList):
        Dependency = {}
        for F in FileList:
            Dependency[F] = self.GetDependencyList(F, ForceInculeList, SearchPathList)
        return Dependency

    ## Find dependencies for one source file
    #
    #  By searching recursively "#include" directive in file, find out all the
    #  files needed by given source file. The dependecies will be only searched
    #  in given search path list.
    #
    #   @param      File            The source file
    #   @param      ForceInculeList The list of files which will be included forcely
    #   @param      SearchPathList  The list of search path
    #
    #   @retval     list            The list of files the given source file depends on
    #
    def GetDependencyList(self, File, ForceList, SearchPathList):
        EdkLogger.debug(EdkLogger.DEBUG_1, "Try to get dependency files for %s" % File)
        EdkLogger.debug(EdkLogger.DEBUG_0, "Including %s" % " ".join(ForceList))
        FileStack = [File] + ForceList
        DependencySet = set()
        MacroUsedByIncludedFile = False

        if self.ModuleInfo.Arch not in gDependencyDatabase:
            gDependencyDatabase[self.ModuleInfo.Arch] = {}
        DepDb = gDependencyDatabase[self.ModuleInfo.Arch]
        while len(FileStack) > 0:
            EdkLogger.debug(EdkLogger.DEBUG_0, "Stack %s" % "\n\t".join(FileStack))
            F = FileStack.pop()

            CurrentFileDependencyList = []
            if F in DepDb and not IsChanged(F):
                CurrentFileDependencyList = DepDb[F]
                for Dep in CurrentFileDependencyList:
                    if Dep not in FileStack and Dep not in DependencySet:
                        FileStack.append(Dep)
            else:
                try:
                    Fd = open(F, 'r')
                except:
                    EdkLogger.error("AutoGen", FILE_OPEN_FAILURE, ExtraData=F)

                FileContent = Fd.read()
                Fd.close()
                if len(FileContent) == 0:
                    continue

                if FileContent[0] == 0xff or FileContent[0] == 0xfe:
                    FileContent = unicode(FileContent, "utf-16")
                IncludedFileList = gIncludePattern.findall(FileContent)

                CurrentFilePath = os.path.dirname(F)
                for Inc in IncludedFileList:
                    # if there's macro used to reference header file, expand it
                    HeaderList = gMacroPattern.findall(Inc)
                    if len(HeaderList) == 1 and len(HeaderList[0]) == 2:
                        HeaderType = HeaderList[0][0]
                        HeaderKey = HeaderList[0][1]
                        if HeaderType in gIncludeMacroConversion:
                            Inc = gIncludeMacroConversion[HeaderType] % {"HeaderKey" : HeaderKey}
                        else:
                            # not known macro used in #include
                            MacroUsedByIncludedFile = True
                            continue
                    Inc = os.path.normpath(Inc)
                    for SearchPath in [CurrentFilePath] + SearchPathList:
                        FilePath = os.path.join(SearchPath, Inc)
                        if not os.path.exists(FilePath) or FilePath in CurrentFileDependencyList:
                            continue
                        CurrentFileDependencyList.append(FilePath)
                        if FilePath not in FileStack and FilePath not in DependencySet:
                            FileStack.append(FilePath)
                        break
                    else:
                        EdkLogger.verbose("%s included by %s was not found in any given path:\n\t%s" % (Inc, F, "\n\t".join(SearchPathList)))

                if not MacroUsedByIncludedFile:
                    if F == File:
                        CurrentFileDependencyList += ForceList
                    #
                    # Don't keep the file in cache if it uses macro in included file.
                    # So it will be scanned again if another file includes this file.
                    #
                    DepDb[F] = CurrentFileDependencyList
            DependencySet.update(CurrentFileDependencyList)

        #
        # If there's macro used in included file, always build the file by
        # returning a empty dependency
        #
        if MacroUsedByIncludedFile:
            DependencyList = [""]
        else:
            DependencyList = list(DependencySet)  # remove duplicate ones
            DependencyList.append(File)

        return DependencyList

    ## Get the root directory list for intermediate files of all modules build
    #
    #   @retval     list    The list of directory
    #
    def GetModuleBuildDirectoryList(self):
        DirList = []
        for Arch in self.PlatformInfo:
            for ModuleAutoGen in self.PlatformInfo[Arch].ModuleAutoGenList:
                DirList.append(ModuleAutoGen.BuildInfo.BuildDir)
        return DirList

    ## Get the root directory list for intermediate files of all libraries build
    #
    #   @retval     list    The list of directory
    #
    def GetLibraryBuildDirectoryList(self):
        DirList = []
        for Arch in self.PlatformInfo:
            for LibraryAutoGen in self.PlatformInfo[Arch].LibraryAutoGenList:
                DirList.append(LibraryAutoGen.BuildInfo.BuildDir)
        return DirList

    ## Return a list of directory creation command string
    #
    #   @param      DirList     The list of directory to be created
    #   @param      MakeType    GNU makefile or MS makefile
    #
    #   @retval     list        The directory creation command list
    #
    def GetCreateDirectoryCommand(self, DirList, MakeType=gMakeType):
        return [gCreateDirectoryCommandTemplate[MakeType] % {'dir':Dir} for Dir in DirList]

    ## Return a list of directory removal command string
    #
    #   @param      DirList     The list of directory to be removed
    #   @param      MakeType    GNU makefile or MS makefile
    #
    #   @retval     list        The directory removal command list
    #
    def GetRemoveDirectoryCommand(self, DirList, MakeType=gMakeType):
        return [gRemoveDirectoryCommandTemplate[MakeType] % {'dir':Dir} for Dir in DirList]

# This acts like the main() function for the script, unless it is 'import'ed into another script.
if __name__ == '__main__':
    pass
