# Copyright (c) 2007, Intel Corporation
# All rights reserved. This program and the accompanying materials
# are licensed and made available under the terms and conditions of the BSD License
# which accompanies this distribution.  The full text of the license may be found at
# http://opensource.org/licenses/bsd-license.php
#
# THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "AS IS" BASIS,
# WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.

#
#This file is used to parse a strings file and create or add to a string database file.
#

import EdkLogger
from UniClassObject import *

DEFINE_STR = '#define'
COMMENT_DEFINE_STR = '// #define'
COMMENT_NOT_REFERENCED = ' // not referenced'
STRING_TOKEN = 'STRING_TOKEN'
H_FILE_HEADER = ['//', '//  DO NOT EDIT -- auto-generated file', '//', \
                 '//  This file is generated by the string gather utility', '//']
LANGUAGE_NAME_STRING_NAME = '$LANGUAGE_NAME'
PRINTABLE_LANGUAGE_NAME_STRING_NAME = '$PRINTABLE_LANGUAGE_NAME'

def DecToHexStr(Dec):
    HexHeader = '0x'
    if Dec < 16:
        return HexHeader + '000' + hex(Dec)[2:].upper()
    elif Dec < 256:
        return HexHeader + '00' + hex(Dec)[2:].upper()
    elif Dec < 4096:
        return HexHeader + '0' + hex(Dec)[2:].upper()
    else:
        return HexHeader + hex(Dec)

def CreateBaseNameDefinition(BaseName):
    Str = ''
    for Item in H_FILE_HEADER:
        Str = WriteLine(Str, Item)
    Str = WriteLine(Str, '#ifndef _' + BaseName.upper() + '_STRINGS_DEFINE_H_')
    Str = WriteLine(Str, '#define _' + BaseName.upper() + '_STRINGS_DEFINE_H_')
    return Str

def CreateStringDefinition(UniObjectClass):
    Str = ''
    ValueStartPtr = 60
    for Index in range(len(UniObjectClass.StringList)):
        Name = UniObjectClass.FindStringObjectNameByToken(Index)
        if Name != None:
            StringItem = UniObjectClass.StringList[Name]
            Line = ''
            if StringItem.Referenced == True:
                Line = DEFINE_STR + Name + ' ' * (ValueStartPtr - len(DEFINE_STR + Name)) + DecToHexStr(StringItem.Token)
            else:
                Line = COMMENT_DEFINE_STR + Name + ' ' * (ValueStartPtr - len(DEFINE_STR + Name)) + DecToHexStr(StringItem.Token) + COMMENT_NOT_REFERENCED
            Str = WriteLine(Str, Line)
    return Str

def CreateHFile(BaseName, UniObjectClass):
    HFile = WriteLine('', CreateBaseNameDefinition(BaseName))
    HFile = WriteLine(HFile, CreateStringDefinition(UniObjectClass))
    HFile = WriteLine(HFile, '#endif')
    return HFile

def CreateCFile(BaseName):
    CFile = ''
    return CFile

def GetFileList(IncludeList, SkipList):
    if IncludeList == None:
        return None
    
    FileList = []
    if SkipList == None:
        SkipList = []
        
    for Dir in IncludeList:
        for File in os.listdir(Dir):
            File = os.path.join(Dir, os.path.normcase(File))
            #
            # Ignore Dir
            #
            if os.path.isfile(File) != True:
                continue
            #
            # Ignore file listed in skip list
            #
            IsSkip = False
            for Skip in SkipList:
                if os.path.splitext(File)[1].upper() == Skip.upper():
                    IsSkip = True
                    break
            
            if not IsSkip:
                FileList.append(File)
    
    return FileList

def SearchString(UniObjectClass, FileList):
    if FileList == []:
        return UniObjectClass
    
    for File in FileList:
        if os.path.isfile(File):
            Lines = open(File, 'r')
            for Line in Lines:
                if Line.find(STRING_TOKEN) >= 0:
                    StrName = Line[Line.find('(', Line.find(STRING_TOKEN)) + len('(') : Line.find(')', Line.find(STRING_TOKEN))].strip()
                    UniObjectClass.SetStringReferenced(StrName)
     
    UniObjectClass.ReToken()
#    for index in range(len(UniObjectClass.StringList)):
#        name = UniObjectClass.FindStringObjectNameByToken(index)
#        if name != None:
#            #print index, str(UniObjectClass.StringList[name])
#            pass
    return UniObjectClass

def GetStringFiles(UniFilList, IncludeList, SkipList, BaseName):
    Status = True
    ErrorMessage = ''
    
    if len(UniFilList) > 0:
        Uni = UniFileClassObject(UniFilList)
    else:
        Status = False
        ErrorMessage = 'No Unicode Files Found'
    
    FileList = GetFileList(IncludeList, SkipList)
    
    Uni = SearchString(Uni, FileList)
    
    if len(Uni.StringList) > 0:
        pass
    
    HFile = CreateHFile(BaseName, Uni)
    CFile = CreateCFile(BaseName)

    return Status, ErrorMessage, HFile, CFile

def Write(Target, Item):
    return Target + Item

def WriteLine(Target, Item):
    return Target + Item + '\n'
    
# This acts like the main() function for the script, unless it is 'import'ed into another
# script.
if __name__ == '__main__':
    UniFileList = ['C:\\Tiano\\Edk\\Sample\\Universal\\UserInterface\\SetupBrowser\\Dxe\\DriverSample\\inventorystrings.uni', 'C:\\Tiano\\Edk\\Sample\\Universal\\UserInterface\\SetupBrowser\\Dxe\\DriverSample\\VfrStrings.uni']
    IncludeList = ['C:\\Tiano\\Edk\\Sample\\Universal\\UserInterface\\SetupBrowser\\Dxe\\DriverSample']
    SkipList = ['.inf', '.uni']
    BaseName = 'DriverSample'
    (s, e, h, c) = GetStringFiles(UniFileList, IncludeList, SkipList, BaseName)
    print h
    print c
